 
### get All fy
GET http://localhost:4000/api/v1/invoice?month=3&year=2026
Content-Type: application/json

### create invoice
POST http://localhost:4000/api/v1/invoice
Content-Type: application/json

{
     "invoiceNumber":"001",
     "issueDate":"2026-03-11T18:16:56.770Z",
     "partyId":"9d7bb86a-8856-474f-885a-ce47b6afd4d5",
     "sgst":9,
     "cgst":9,
     "igst":0,
     "status":"SENT",
     "financialYearId":"2025-26",
     "items":[
          {
          "description":"testing description", 
          "hsnCode":"784651",
          "unit":"KG",
          "quantity":10,
          "rate":1000
          }
     ]
}
 