
###  get
GET http://localhost:4000/api/v1/reports/party/outstanding
Content-Type: application/json

###  get
GET http://localhost:4000/api/v1/reports/party/receivable
Content-Type: application/json

###  get
GET http://localhost:4000/api/v1/reports/party/payable
Content-Type: application/json

###  get
GET http://localhost:4000/api/v1/reports/party/party-statement?partyId=9d7bb86a-8856-474f-885a-ce47b6afd4d5
Content-Type: application/json


# 9edd20f1-bc16-4492-9a82-478137c0711e

### get All fy
GET http://localhost:4000/api/v1/reports/fy
Content-Type: application/json

### set Active
PATCH  http://localhost:4000/api/v1/reports/fy/bec28e8e-29c2-438f-86f1-6cfef81e0b32/active
Content-Type: application/json

### Post Request
POST http://localhost:4000/api/v1/reports/fy
Content-Type: application/json

{
 "label": "2026-27",
 "startDate": "2026-04-01",
 "endDate": "2027-03-31"
}


### delete Request
DELETE  http://localhost:4000/api/v1/reports/2
Content-Type: application/json
 